### ISSUE TITLE
Mesh generated by the demo.yaml file doesn't work

### ISSUE THREAD

**Issue by bduartee** [ActiveVisionLab/ray-onet#1]
After creating the conda env and compiling the extension modules, in order to test your code on the provided input images in the demo folder, I used `python generate.py configs/demo.yaml` .
The mesh created for all the demo folder's images is like this one:

![00_mesh](https://user-images.githubusercontent.com/94623508/142432181-54c62f15-dd38-4627-b5bc-a75ab4e3aa0f.png)

Can anyone help me with this issue? 
Thank you for your attention

**Comment by bianwenjing** [comment]
Did you download the pre-trained model and set cfg['test']['model_file']?

**Comment by bduartee** [comment]
Thank you for your response. 
Yes, I downloaded the pre-trained model named 'model_best.pt' and added it to the 'rayonet' folder before generating the meshes. Besides that I also appended ['test']['rayonet/model_best.pt']  on the demo.yaml file. I'm not understanding what I'm doing wrong.

**Comment by bianwenjing** [comment]
I still suspect the pre-trained model is not loaded correctly.  Please set `cfg['test']['model_file']` (not `cfg['test']['rayonet/model_best.pt']`) to the absolute path to model_best.pt and check when you run `python generate.py configs/demo.yaml` the path printed on the screen is the path to the **pre-trained** model_best.pt. I ran the model myself and got the result shown below.


<img width="964" alt="Screenshot 2021-11-22 at 4 13 13 PM" src="https://user-images.githubusercontent.com/39569160/142896174-0f9ceb49-e8b1-4072-8012-88191ad48303.png">

**Comment by bduartee** [comment]
Thank you for your attention!
I've done that before and I confirm that when I run `python generate.py configs/demo.yaml` the path printed is the absolute path to the pre-trained model_best.pt. The results are still the same. 

In which .yaml file should this `cfg['test']['model_file']` be? Because demo.yaml doesn't even have a `cfg['test']`. I suppose it should be on the default.yaml file, right? But there's also another file invoked there on `cfg[training][load_dir] = model.pt` that I don't understand where it comes from. Could you explain what's this `model.pt` file?

**Comment by bianwenjing** [comment]
You can add `cfg['test']['model_file']` to `demo.yaml`, which is path for loading model during testing. Otherwise, the path for loading model is the one in `default.yaml`. `model.pt` is the checkpoint saved every `cfg['training']['checkpoint_every']` iterations during training.  `model_best.pt` is the model with the best evaluation result saved during training. `cfg['training']['load_dir']` makes `model.pt` loaded when resuming training.

Regarding your problem, if you didn't change any parameter (i.e. threshold) and load the `model_best.pt` correctly, the result shouldn't be wrong... Another guess is the `model_best.pt` is overwritten by another checkpoint if you carried out training before. Please download the pre-trained model again if this is the case. Otherwise, I suggest you visualise the output from the model to see if the problem is within the model or during mesh extraction.

**Comment by bduartee** [comment]
Thank you for your explanation.
I've already tried to implement this on Windows and I'm currently trying to implement it on Linux since I was afraid it was something related to the OS. I've successfully created the env. , with the dependencies versions requested on the `environment.yaml`, but I'm getting an issue when I run `python generate.py configs/demo.yaml` (with the absolute path to model_best.pt):

> RuntimeError: CUDA error: no kernel image is available for execution on the device

Could you please inform me which version of Pytorch and Cuda you used on your project?

**Comment by bianwenjing** [comment]
Pytorch 1.4.0 + cuda 10.1

**Comment by bduartee** [comment]
I managed to reproduce the demo meshes on Linux using pytorch= '1.9.0+cu111'. (Cuda version= 11.1). 

Although the `python generate.py configs/demo.yaml` is running now, when I try to run `python setup.py build_ext --inplace`, there's an error related with `im2mesh.utils.libkdtree.pykdtree.kdtree'. I will open another issue related to this problem.

Edit: Solved the problem that appeared when I ran `python setup.py build_ext --inplace`, using this suggestion: https://github.com/autonomousvision/occupancy_networks/issues/96#issuecomment-818522473

**Comment by gokceay** [comment]
> I still suspect the pre-trained model is not loaded correctly. Please set `cfg['test']['model_file']` (not `cfg['test']['rayonet/model_best.pt']`) to the absolute path to model_best.pt and check when you run `python generate.py configs/demo.yaml` the path printed on the screen is the path to the **pre-trained** model_best.pt. I ran the model myself and got the result shown below.
> 
> <img alt="Screenshot 2021-11-22 at 4 13 13 PM" width="964" src="https://user-images.githubusercontent.com/39569160/142896174-0f9ceb49-e8b1-4072-8012-88191ad48303.png">

Hi, 

Eventhough I have done what you have said and check the printed path for the model_best.pt path and they are the same, I keep having pyramids. Could you help me regarding the issue? I have added these to the demo.yaml:

test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: true
  model_file: /pathtothe/demo/model_best.pt
