### ISSUE TITLE
Question about the scaling factor

### ISSUE THREAD

**Issue by AlbertoRemus** [ActiveVisionLab/ray-onet#4]
Hello, I've found this work really interesting and I would like to ask a question about the scaling factor in your framework.

From the paper I can find the following paragraphs:

about training:
![Screenshot from 2022-05-02 14-42-27](https://user-images.githubusercontent.com/54797872/166235374-8798992b-8c49-4d2e-94e7-e6652dd791d7.png)

and inference:
![Screenshot from 2022-05-02 14-19-01](https://user-images.githubusercontent.com/54797872/166235175-3dc5ec7d-2b22-4ec0-b8ba-d4b15d8fb652.png)

So is the inferred 3D model mesh generated up-to-scale? In practice the scaling calibration during training is just used to improve shape reconstruction results, yet leaving the scale factor unknown during inference, isn't it?

Thanks in advance.

**Comment by bianwenjing** [comment]
Yes. The scale factor is just used to avoid scale ambiguity during training(because the ground truth models have certain scales). During testing, it can be set to a random number (preferably within the range of the scale factors trained).

**Comment by AlbertoRemus** [comment]
@bianwenjing many thanks for the clarification, I will close the issue then
